###
#Create a new post

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "Siu",
    "content": "Siuuuuuuuuuuuuuuuuuu",
    "author": "CR7"
}

###
#Get all posts

GET http://localhost:5000/post

###
#Get a post by id

GET http://localhost:5000/post/67488c842d03659f5385c2b

###
#Get a all posts by author

GET http://localhost:5000/post?author=Or Natan


###
#Update a post by id

PUT http://localhost:5000/post/674dafea2ee60d889576b291
Content-Type: application/json

{
    "title": "Hi",
    "content": "Hello!",
    "author": "Elad Rabinovich"
}


###
#Delete a post by id

DELETE  http://localhost:5000/post/674dd81ffb80a497e994688d

###

###
#Create a new comment

POST http://localhost:5000/comment
Content-Type: application/json

{
    "PostId": "675741b8ebba9bd796445df5",
    "content": "SIUUUUUU",
    "author": "CR7 Mashiah"
}

###
#Get all comments

GET http://localhost:5000/comment


###
#Get a comment by id

GET http://localhost:5000/comment/675741b8ebba9bd796445df5