###
#Create a new post

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "123",
    "content": "456",
    "author": "Matan Bar"
}

###
#Get all posts

GET http://localhost:5000/post

###
#Get a post by id

GET http://localhost:5000/post/67488c842d03659f5385c2ba
